version: 1.0.{build}
image: Visual Studio 2019
build_script:
- cmd: dotnet build IchigoRankCalculator/IchigoRankCalculator.sln
test_script:
- cmd: dotnet test IchigoRankCalculator/IchigoRankCalculator.sln
